### ISSUE TITLE
test-suite fails on Fedora

### ISSUE THREAD

**Issue by martinkg** [tiliado/diorite#12]
i changed this on my rpm spec file to build the test-suite:
...
%build
VALAFLAGS=--quiet waf configure --with-experimental-api \
          --prefix=%{_prefix} \
          --libdir=%{_libdir}
waf build --prefix=%{_prefix} \
          --libdir=%{_libdir}

%install
waf install --no-ldconfig --prefix=%{_prefix} \
            --libdir=%{_libdir} \
            --destdir=%{buildroot}

%check
LD_LIBRARY_PATH=./build ./build/run-dioritetests-0.3
....

but the compilaton fails with:

[ 62/114] Compiling build/main.c
[ 63/114] Compiling build/KeyValueStorage.c
[ 64/114] Compiling build/Dialogs.c
[ 65/114] Compiling build/run-dioritetests-0.3.c
In file included from ./dioritetests-0.3.h:8:0,
                 from run-dioritetests-0.3.c:9:
./dioriteglib-0.3.h:14:38: fatal error: gio/gfiledescriptorbased.h: No such file or directory
 #include <gio/gfiledescriptorbased.h>
                                      ^
compilation terminated.

to compile it on Fedora the following changes are necessary

```
--- wscript.orig	2017-04-18 17:10:41.940079460 +0200
+++ wscript		2017-04-18 15:46:27.868186780 +0200
@@ -304,8 +305,8 @@
 		ctx.program(
 			target = RUN_DIORITE_TESTS,
 			source = [ctx.path.find_or_declare("%s.vala" % RUN_DIORITE_TESTS)],
-			packages = "gio-2.0 glib-2.0",
-			uselib = "GIO GLIB",
+			packages = "gio-2.0 glib-2.0 gio-unix-2.0",
+			uselib = "GIO GLIB UNIXGIO",
 			use = [DIORITE_GLIB, DIORITE_GTK, DIORITE_DB, DIORITE_TESTS],
 			vala_defines = vala_defines,
 			defines = ['G_LOG_DOMAIN="DioriteTests"'],
```

**Comment by fenryxo** [comment]
Hello @martinkg. Thanks for your patch. This issue is a bit weird as the RUN_DIORITE_TESTS target doesn't use gio-unix-2.0 at all. It seems that your version of waf no longer inherits dependencies from libs in `use = [DIORITE_GLIB, DIORITE_GTK, DIORITE_DB, DIORITE_TESTS]`. Not sure whether that is the intended behavior or a bug. Anyway, I'll take your patch into consideration for #13.
