### ISSUE TITLE
Upgrade waf and re-create wscript

### ISSUE THREAD

**Issue by fenryxo** [tiliado/diorite#13]
wscript contains a lot of legacy nonsense and requires waf 1.7.14. Let's create a new one from scratch.

- [x] Upgrade [waf](https://waf.io/) to the latest stable (1.9.x)
- [x] Raise deps to match Nuvola
- [x] Set Python 3 as default
- [x] Remove platform option as windows support is dead for a long time
- [x] Don't call ldconfig (add info to readme instead).
- [x] Don't create version-info.txt (flatpaks are built from git anyway)
- [x] Remove --with-experimental-api and just build it as we do in flatpak builds to run tests. Nuvola will need dioritedb for cross-service track rating database
- [x] Noop in recent vala: ctx.env.append_value("VALAFLAGS", "--thread") 
- [x] Downstream can set env variable:  ctx.env.append_unique('CFLAGS', '-O0')
- [x] '--quiet' option might not be specified in VALAFLAGS #11 
- [x] Examine: test-suite fails on Fedora #12 
- [x] Try to upstream the `@extension('.vapi')`rule

**Comment by voxik** [comment]
Thank you! I appreciate that 👍 

Unfortunately, there seems to be minor issue in the recent Waf: waf-project/waf/issues/1948

**Comment by fenryxo** [comment]
I know about it. That's why I bundled waf from git master instead of the official 1.9.9 release.

**Comment by voxik** [comment]
Confusing. I did:

```
$ ./waf --version
waf 1.9.10 (ae3f254315e0dcea4059703987148882ba414894)
```

and checked the hash, which appears to be 8 days old, but checking the expanded waf, the fix is apparently there.

Glad this is not issue for you and appreciate your work!

**Comment by fenryxo** [comment]
Well, git is known to be perfect at rewriting history ;-)

**Comment by fenryxo** [comment]
Try to upstream the `@extension('.vapi')`rule → PR waf-project/waf#1949

**Comment by fenryxo** [comment]
Try to upstream the @extension('.vapi')rule → merged
