### ISSUE TITLE
Synchronize version with Nuvola

### ISSUE THREAD

**Issue by fenryxo** [tiliado/diorite#14]
To be less confusing which version of diorite is required for a particular version of Nuvola

* Nuvola 4.0, Diorite 4.0, Nuvola SDK 4.0
* Nuvola 4.1, Diorite 4.0, Nuvola SDK 4.1 (No new diorite release)
* Nuvola 4.2, Diorite 4.2, Nuvola SDK 4.2 (Diorite 4.1 skipped)

**Comment by martinkg** [comment]
Can you tell me, which nuvolaplayer version is required for diorite-0.3.3 and nuvolasdk-1.3.0
Or have you a matrix for corresponding 3.x version ?

**Comment by fenryxo** [comment]
No nuvolaplayer version is required for for diorite, the dependency is the other way aground. The matrix is:

* **Nuvola 3.0.x Stable Releases** require Diorite 0.2.x stable releases in the version as specified in Nuvola's README.md or wscript, e.g. Nuvola 3.0.8 requires Diorite 0.2.2
* **Nuvola 3.1.x Rolling Releases** require Diorite 0.3.x development releases in the version as specified in Nuvola's README.md or wscript, e.g. Nuvola 3.1.2 requires Diorite 0.3.3
* **Nuvola SDK** 1.3.0 can build scripts compatible with both Nuvola 3.0.8 and 3.1.2.


As a rule of thumb: Always use either the latest releases of Diorite 0.2.x + Nuvola 3.0.x + Nuvola SDK or the latest development snapshots of Diorite 0.3.x + Nuvola 3.1.x + Nuvola SDK.

However, the only thing I can guarantee is that the latest git master commit of Nuvola builds with the latest git master commit of Diorite and Nuvola SDK because that's how flatpaks are built and tested.

**Comment by martinkg** [comment]
many thanks for the clarify words and the matrix.

**Comment by fenryxo** [comment]
FYI, Nuvola 4.x will also be rolling series with monthly or bimonthly tagged snapshots (4.0, 4.1, 4.2, ....).

**Comment by fenryxo** [comment]
Nuvola's builds are going to change version scheme in the next release later this month: 

* Nuvola `3.1.4+n` → `3.1.4.n` → `(3+1).4.n` →  `4.4.n`. (`n` is the number of commits since the last tag.)
* Nuvola 4.0 is rescheduled as Nuvola 5.0.

The version of Diorite & Nuvola SDK is going to be kept in sync with Nuvola.

**Comment by fenryxo** [comment]
Diorite, Nuvola SDK and Nuvola Runtime 4.4.0 are out.
