### ISSUE TITLE
diorite-4.10.0 a lot of compilation warnings on Fedora 28 with vala 0.40.0

### ISSUE THREAD

**Issue by martinkg** [tiliado/diorite#24]

**Comment by martinkg** [comment]
a lot of compilation warnings on Fedora 28 with diorite-4.10.0 and vala-0.40.0
[warnings-f28.txt](https://github.com/tiliado/diorite/files/1831195/warnings-f28.txt)

**Comment by fenryxo** [comment]
Thanks, closing in favor of #20.
