### ISSUE TITLE
Permission denied (HTTP 403) for package repository

### ISSUE THREAD

**Issue by scotte** [tiliado/diorite#5]
It looks like there's a permission problem for libdiorite in the package repository, and as a result I have been unable to update nuvolaplayer to the latest version:

```
The following NEW packages will be installed:
  libdiorite0.3{a}
The following packages will be upgraded:
  nuvolaplayer3
1 packages upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 523 kB of archives. After unpacking 638 kB will be used.
Do you want to continue? [Y/n/?]
Get: 1 https://tiliado.eu/nuvolaplayer/repository/deb/ jessie/devel libdiorite0.3 amd64 0.3.0~201512301553.57287c9-0+1~jessie [144 kB]
Err https://tiliado.eu/nuvolaplayer/repository/deb/ jessie/devel libdiorite0.3 amd64 0.3.0~201512301553.57287c9-0+1~jessie
  HttpError403
Get: 2 https://tiliado.eu/nuvolaplayer/repository/deb/ jessie/devel nuvolaplayer3 amd64 3.1.0~201512301807.d865d68-0+1~jessie [379 kB]
Err https://tiliado.eu/nuvolaplayer/repository/deb/ jessie/devel nuvolaplayer3 amd64 3.1.0~201512301807.d865d68-0+1~jessie
  HttpError403
0% [Working]E: Failed to fetch https://tiliado.eu/nuvolaplayer/repository/deb/pool/devel/d/diorite/libdiorite0.3_0.3.0~201512301553.57287c9-0+1~jessie_amd64.deb: HttpError403
```
Or directly:
```
$ wget  'https://tiliado.eu/nuvolaplayer/repository/deb/pool/devel/d/diorite'/libdiorite0.3_0.3.0~201512301553.57287c9-0+1~jessie_amd64.deb
--2016-01-03 12:27:46--  https://tiliado.eu/nuvolaplayer/repository/deb/pool/devel/d/diorite/libdiorite0.3_0.3.0~201512301553.57287c9-0+1~jessie_amd64.deb
Resolving tiliado.eu (tiliado.eu)... 31.31.78.89
Connecting to tiliado.eu (tiliado.eu)|31.31.78.89|:443... connected.
HTTP request sent, awaiting response... 403 FORBIDDEN
2016-01-03 12:27:47 ERROR 403: FORBIDDEN.
```
Thanks!

**Comment by fenryxo** [comment]
Hello. The permissions are correct. The **Nuvola Player 3.1 Rolling Releases repository** requires authentication with a Tiliado account. You can do it with [Tiliado Repository Installer](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html#add-nuvola-player-repository) or [manually](https://tiliado.eu/nuvolaplayer/repository/#repository-authentication). Alternatively, you can switch to the **Nuvola Player 3.0 Stable Releases repository**, which doesn't require authentication.

**Comment by scotte** [comment]
Ah, thanks - I was unaware that this was intended behavior. Do note that this means the debian package repository won't work via apt for devel version, since it doesn't have a way (that I know of) to do repo-specific authentication. Switching to the stable release resolved it for me, and I can use the source if I need devel version again. Thanks!

**Comment by fenryxo** [comment]
> Ah, thanks - I was unaware that this was intended behavior.

It has been mentioned in the announcement of 3.0 Stable Releases and 3.1 Rolling Releases. Maybe I should it make more clear.

> Do note that this means the debian package repository won't work via apt for devel version, since it doesn't have a way (that I know of) to do repo-specific authentication.

HTTP Basic Auth `https://USERNAME:TOKEN@tiliado.eu/...`, which is used by the repository, is fully supported by apt.

**Comment by scotte** [comment]
> Maybe I should it make more clear.

Or maybe I should read the announcements and release notes. :-)

> HTTP Basic Auth [...] is fully supported by apt.

Ah, yeah - that's obvious now that I see it. :-/

Thanks!
