### ISSUE TITLE
Do not install development dependencies on Fedora

### ISSUE THREAD

**Issue by voxik** [tiliado/diorite#6]
It seems that diorite pulls in glib2-devel on Fedora. This is obviously development library and should not be needed. Checking the package dependencies:

```
$ sudo dnf repoquery --requires diorite0.2
Last metadata expiration check: 0:31:49 ago on Tue Apr 12 12:56:33 2016.
/sbin/ldconfig
/usr/bin/pkg-config
/usr/bin/python3
libX11.so.6()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libdioriteglib-0.2.so()(64bit)
libgdk-3.so.0()(64bit)
libgdk_pixbuf-2.0.so.0()(64bit)
libgio-2.0.so.0()(64bit)
libglib-2.0.so.0()(64bit)
libgobject-2.0.so.0()(64bit)
libgtk-3.so.0()(64bit)
libpango-1.0.so.0()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
pkgconfig(dioriteglib-0.2)
pkgconfig(glib-2.0)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
rtld(GNU_HASH)
```

This is very likely caused by the dependency on `pkgconfig(glib-2.0)`, which is there due to inclusion of pkgconfig files. As per Fedora guidelines [1], these files should be placed into -devel subpackage and this would avoid this dependency.

But this is just my guess, since I cannot find the .spec files anywhere ....

[1] https://fedoraproject.org/wiki/Packaging:Guidelines#Pkgconfig_Files_.28foo.pc.29
##

**Comment by fenryxo** [comment]
Hello @voxik. Thanks for taking the time to report this issue. Indeed, Diorite library is currently built as a single package without a `-devel` sub-package.

**Comment by fenryxo** [comment]
I'm closing this issue as [Nuvola 3.1 Milestone 2 deprecates DEB/RPM packages in favor of cross-distribution flatpaks](https://medium.com/nuvola-news/nuvola-3-1-milestone-2-deprecates-deb-rpm-packages-in-favor-of-flatpaks-and-officially-supports-579534c3b75c) and no improvements are planned for the current DEB/RPM packaging.

**Comment by voxik** [comment]
Probably time to prepare my own RPMs .... But thx for Nuvola development 👍

**Comment by fenryxo** [comment]
> Probably time to prepare my own RPMs

Sure. I don't have time to do that any more but community RPM builds are welcome 👍
